#!/usr/bin/env php
<?php
/**
 * Pusher
 *
 * @author mybsdc <mybsdc@gmail.com>
 * @date 2019/3/2
 * @time 11:05
 * @link https://github.com/luolongfei/pusher
 */

error_reporting(E_ERROR);
ini_set('display_errors', 1);
set_time_limit(0);

define('IS_CLI', PHP_SAPI === 'cli' ? true : false);
define('DS', DIRECTORY_SEPARATOR);
define('ROOT_PATH', realpath(__DIR__));
define('VENDOR_PATH', realpath(ROOT_PATH . '/vendor'));
define('APP_PATH', realpath(ROOT_PATH . '/app'));
define('RESOURCES_PATH', realpath(ROOT_PATH . '/resources'));

date_default_timezone_set('Asia/Shanghai');

/**
 * 注册错误处理
 */
register_shutdown_function('customize_error_handler');

/**
 * 注册异常处理
 */
set_exception_handler('exception_handler');

require VENDOR_PATH . '/autoload.php';

use Luolongfei\Lib\Log;
use Luolongfei\App\Console\Pusher;
use Luolongfei\Lib\Mail;

/**
 * @throws Exception
 */
function customize_error_handler()
{
    if (!is_null($error = error_get_last())) {
        Log::error('程序意外终止', $error);
//        Mail::send('主人，程序意外终止', '具体情况我也不知道，请查看服务器日志定位问题。');
    }
}

/**
 * @param $e
 *
 * @throws \Exception
 */
function exception_handler(\Exception $e)
{
    Log::error('未捕获的异常：' . $e->getMessage());
    Mail::send('主人，未捕获的异常', "具体的异常内容是：\n" . $e->getMessage());
}

try {
    /**
     * php run.php --session=vbot
     */
    Pusher::instance()->handle();
} catch (\Exception $e) {
    Log::error('执行出错：' . $e->getMessage(), $e->getTrace());
}
